"""
Generates a student list JSON file for create_and_share_google_docs.py from a CSV
downloaded from the Canvas gradebook.

Usage:
    canvas2json.py FILENAME.csv [-o output.json]

Where FILENAME.csv is a CSV exported from Canvas's gradebook containing only students.
"""

import argparse
import csv
import json
import sys
from pathlib import Path


def is_valid_student(row):
    """
    Returns True if the row in the CSV generated by Canvas refers to a valid student.

    Canvas generates two annoying rows in its CSV:
     1. Points Possible -- the row immediately after the header
     2. Student, Test -- automatically enrolled test student.

    Luckily, it's easy to detect either of them;
    the "SIS User ID" column (corresponding to a ualberta CCID) will be falsey.
    """
    return bool(row["SIS User ID"])


def to_json_format(row):
    full_name = row["Student"]
    ccid = row["SIS Login ID"]
    email = f"{ccid}@ualberta.ca"
    surname, _, prename = full_name.partition(", ")
    return dict(prename=prename, surname=surname, email=email)


def dump_json(student_list, out_file):
    json.dump(student_list, out_file)
    print(file=out_file)


if __name__ == "__main__":
    # Parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument("filename", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()

    # Read and parse the CSV
    with args.filename.open(encoding="UTF-8") as csv_file:
        reader = csv.DictReader(csv_file)
        student_list = [to_json_format(row) for row in reader if is_valid_student(row)]

    # Dump as JSON
    if output := args.output:
        with output.open("w", encoding="UTF-8") as out_file:
            dump_json(student_list, out_file)
    else:
        dump_json(student_list, sys.stdout)
